### ISSUE TITLE
Archive this project

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess-operator#20]
Per https://github.com/vitessio/vitess/issues/5713 we plan to archive this repository.

This issue is to track:
- Updating the readme pointing to Vitess helm charts as an upgrade path.
- Archiving this project.

**Comment by hallaroo** [comment]
Added deprecation notice on Jun 11th https://github.com/vitessio/vitess-operator/commit/3e5ab51f43af6de45f98c407cb442d72006c509d

December 11th was six months. 

I will check in with @deepthi after the holidays to see what needs to be done here.
