### ISSUE TITLE
status

### ISSUE THREAD

**Issue by kfox1111** [vitessio/vitess-operator#4]
What is the current production readiness status of the operator? Is it ok to use? Is upgrades supported? Is the api stable?

**Comment by Bessonov** [comment]
Last commit is 7 months ago...

**Comment by derekperkins** [comment]
We just started development using the Operator SDK, so hopefully this repo picks up steam. For now, the helm chart in the main repo is the best place to start, and that's what the getting started examples use.

**Comment by Bessonov** [comment]
Worth to mention this [WIP PR comment](https://github.com/vitessio/vitess/pull/4194#issuecomment-420353133).

@derekperkins is there any place like roadmaps, ETA and so on to track the progress?

**Comment by derekperkins** [comment]
In the short term, @carsonoid is working on it here https://github.com/carsonoid/vitess-operator/tree/refactorgo. Once it gets PR'ed into this repo and becomes a little more stable, we'll flesh out more of the roadmap here. The current push is to get feature parity with the helm chart.
